[package]
name = "pitchdetector"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pitch-detector = "0.3.1"
anyhow = "1.0.75"
float-cmp = "0.9.0"
hound = "3.5.1"
libc = "0.2.149"
